DELETE http://localhost:3005/api/notes/2

###

GET http://localhost:3005/api/notes

###

GET http://localhost:3005/api/notes/100

###

POST http://localhost:3005/api/notes
content-type: application/json

# {
#     "content": "sample",
#     "important": "false"
# }

{   "content": "samp",
    "important": "false"
}

###
PUT  http://localhost:3005/api/notes/685d03c042cb4783470d350b
content-type: application/json

{
    "content": "sample note",
    "important": "false"
}

##update garda dinxa tara error handle(meaning sam minlength yo error tw catch ) gardainw schema le 

# {   "content": "sam",
#     "important": "false"
# }