DELETE http://localhost:3005/api/notes/2

###

GET http://localhost:3005/api/notes

###

GET http://localhost:3005/api/notes/100

###

POST http://localhost:3005/api/notes
content-type: application/json

# {
#     "content": "sample",
#     "important": "false"
# }

{   "content": "samp",
    "important": "false"
}

###
PUT  http://localhost:3005/api/notes/685d03c042cb4783470d350b
content-type: application/json

{
    "content": "sample note",
    "important": "false"
}

##update garda dinxa tara error handle(meaning sam minlength yo error tw catch ) gardainw schema le 

# {   "content": "sam",
#     "important": "false"
# }

###
POST  http://localhost:3005/api/users/
content-type: application/json

{   
    "username": "Ram",
    "name":"Ram Tolange",
    "password": "password123"
}

###686a6b6a0de5f106f5c9a2cb
### for post 
POST http://localhost:3005/api/notes
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbSIsImlkIjoiNjg2YTZiNmEwZGU1ZjEwNmY1YzlhMmNiIiwiaWF0IjoxNzUxODc2NzU4LCJleHAiOjE3NTE4NzY3ODh9.8234oOGqmvysyQ080YW85N1WHcwPkBbV_Rf2CDF8Vug

{   
    "content": "note creation using token ",
    "important": "false",
    "userId": "686a6b6a0de5f106f5c9a2cb"
} 

###
POST  http://localhost:3005/api/login/
content-type: application/json

{   
    "username": "Ram",
    "password": "password123"
}

###
POST  http://localhost:3005/api/users/
content-type: application/json


{   
    "username": "Ram",
    "name":"Ram Tolange",
    "password": "password123"
}